travis:
  secure:
    BINSTAR_TOKEN: RhPtFLedBIF0xXQh8GNvW6V6cO2VAMIi1A2XWLhfR6cm6lNByXYPglX5XtizaPQQ3TXz/JzEDOeqd4M9RDwhEPtkd3fMPNPt7NnlFa1j4EJXDf+vDMhG4SKiwaXitAgNyO5de8CKVCqpZporJwnIy1Y4VaSarNMxsQnYyW0tmHKIWAlpEIlDEkP0rkkQyEPUUMnbGknjFvs2E+sU4+UhoswfaR3k4NMCHxTpLgy+W8a9tDPzPCyy4nVPXVECUq+pNT0+3tLZD0Tv5Ek19xqZIsQxNDppC3Az5vYmcnARcbxooMfdUUDNofT/5d8rXKuDfd9tGX1dzPoNcr+FX5OO+2/8uvwWcrIfjSjkNlU+rOlTIB9aymuezfr4c+ZHcgl9gGnOxggr+zLMJFF9/O1snQoNnTX65PG1t9Vzb0R+b5HsPDWALO81VPsdZmFHd03qUH6OdePfrqSR8XW9eiocAw5QdFO3OK9OYRw4GJAv/FiIrHTaV9zkPbnFIhfTm+4q4jTh5KgHkGZPtN+kaCJjucLvYtuD2amHTckXVoHd774/HUCldosKjWBed4GX+Gm6g3MXyULKwG0uIa+JEez3tEAaCNotyaKe0FpZ4rxtCXqrbP0WgOrVD9fZlSG7ch31fRsr2GmJp0U6bkpyaZ6heyVV6zI51jtYQWKVUeEgVA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
