travis:
  secure:
    BINSTAR_TOKEN: oFpfyJ2U4dj1icVUOBtMNH2cw1iJShLDdZ1N0mDzwafD+679+Fq49LvcGZCCuGjTkErsRF9g0mD0FuoTLalNlilpp5mbrRQ1RgvfhJ/SAB8woBWms4QnldHXRh0gAgXRl/uOVKGVPUwMw+VlQZZDi81Cadw66Fs50Mf+RSWptILnp0lu4Vq4V0/kECZ8Kxm3Kds1xNPmKNgnbkjXaSRdjxNUhhbWFOkTvLpcnmKbR1uOm2I32EEkcsNnT3tz/BHvtgL323Vw7EyZpRSU0y3KYqmRNYQRB0tvsBkxinJCCqmXghi0VU/qOZhnLH6xNqAaJ1seiPTmUSb9iuoigRw7KCNnZxWFKEU1v2dymUPSkl/HhsI0cEUcWvzidu8Jvv2A8Em9oOj7dUcE+TxSxvaJGjeAFTWBGIDZpt3T7rT2EabiJkCrOBY1Vi0o61v50PcUmKSF3fg8ghPFXRA2/e9+QYcFD38R6fYl4LCEc/j4F11R/ztv3y34qrlbbmmag0MTEIIEZagZBlhxITXH0K+yQaNKwUJL0crNs+TjtDSZyHxwleBbIMjPqVplGLRncBuo3WxHPw9cQWV/PYxGURcPtoG55BepLML1FOeGv37DpyB2MpLiWMuHLW3R8NGiD8Qj5M7E4Uqdp69gK8GY4Ow626KgXeHUbRrokoRjPNGgHME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
